import subprocess

from ksproject_utils.plugin import CommandPlugin
from ksproject_utils.gradle.gradle_project import GradleProject, GradleProjectError, _ARCH_TO_PLATFORM_CLS
from ksproject_utils.pip_install import UV, PipInstaller, collect_local_paths, PipInstallError
from ksproject_utils.xcode.xcode_project import XcodeProject
from ksp_bootstraps.platforms import Platform

import argparse
from pathlib import Path
import tomllib
import shutil

from .target_selector import select_target, TargetSelectionError, Target

class PipInstallerOverride(PipInstaller):

    @staticmethod
    def install(uv_src: str, platform: Platform, site_packages: str) -> None:
        print(f"[SimplePlugin] Installing {uv_src} to {site_packages} for platform {platform}")
        project_dir = Path(uv_src).resolve()
        if UV is None:
            raise Exception("no uv toolchain")

        command = [
            UV,
            "pip",
            "install",
            uv_src,
            "--python-platform",
            platform.pip_platform,
            "--index-strategy",
            "unsafe-best-match",
            "--target",
            site_packages,
        ]
        # The target is reused between builds.  Without reinstalling local
        # path packages, uv may keep a cached wheel when their version has not
        # changed, leaving Android with stale development code.
        for package_name in collect_local_package_names(project_dir):
            command.extend(("--reinstall-package", package_name))

        try:
            subprocess.check_call(command)
        except subprocess.CalledProcessError as e:
            raise PipInstallError(f"Failed to install '{uv_src}': {e}")

        # Copy .java / .libs / .kotlin / .gradle from local dep source trees into
        # site_packages.  These dot-directories are not included in wheels, so
        # ksproject collects them.  (.gradle contains JSON files generated by
        # ksp-builder with gradle_dependencies and permissions for each package.)
        sp = Path(site_packages)
        all_paths = [project_dir] + collect_local_paths(project_dir)
        for local_path in all_paths:
            for dot_dir in (".java", ".libs", ".kotlin", ".gradle"):
                src = local_path / dot_dir
                if src.is_dir():
                    shutil.copytree(src, sp / dot_dir, dirs_exist_ok=True)


class OverrideProject(GradleProject):

    def __init__(self):
        super().__init__()

    def install_site_packages(self) -> None:
        """Install the project (and its deps) into per-arch site_packages dirs."""
        for arch in self.android_data.archs:
            cls = _ARCH_TO_PLATFORM_CLS.get(arch)
            if cls is None:
                raise GradleProjectError(f"No AndroidPlatform mapping for arch {arch}")
            platform = cls(str(self.project_path))
            Path(platform.site_packages).mkdir(parents=True, exist_ok=True)
            PipInstallerOverride.install(
                uv_src=str(self.project_path),
                platform=platform,
                site_packages=platform.site_packages,
            )

    def build(
            self,
            variant: str = "debug",
            aar: bool = False,
            bundle: bool = False,
            clean: bool = False,
        ) -> list[Path]:

        print(f"[SimplePlugin] Building project at {self.project_path} with variant={variant}, aar={aar}, bundle={bundle}, clean={clean}")

        return super().build(variant=variant, aar=aar, bundle=bundle, clean=clean)

def collect_local_package_names(project_dir: Path) -> list[str]:
    """Return distribution names for the project and local path dependencies."""
    package_names: list[str] = []
    for package_dir in [project_dir, *collect_local_paths(project_dir)]:
        pyproject = package_dir / "pyproject.toml"
        if not pyproject.exists():
            continue

        with pyproject.open("rb") as f:
            data = tomllib.load(f)

        package_name = data.get("project", {}).get("name")
        if package_name and package_name not in package_names:
            package_names.append(package_name)

    return package_names

class SimpleCommands:

    def register(self, subparsers: argparse._SubParsersAction) -> None:
        # By the time plugins run (see KSProjectCLI.register_plugins), the
        # "android" and "apple" subcommands have already been registered by
        # GradleCommands/AppleCommands. We hook into their existing
        # sub-subparsers to add a "simple" leaf command to each, rather than
        # registering "simple" as a new top-level subcommand.
        android = subparsers.choices.get("android")
        if android is not None:
            android_sub = self._find_subparsers_action(android)
            simple = android_sub.add_parser("simple", help="Build, install and run with sensible defaults")
            simple.set_defaults(func=self.run_gradle)

        apple = subparsers.choices.get("apple")
        if apple is not None:
            apple_sub = self._find_subparsers_action(apple)
            for plat in ["ios", "macos", "sim"]:
                plat_parser = apple_sub.choices.get(plat)
                if plat_parser is not None:
                    plat_sub = self._find_subparsers_action(plat_parser)
                    simple = plat_sub.add_parser("simple", help=f"Build, install and run on {plat} with sensible defaults")
                    match plat:
                        case "ios":
                            simple.set_defaults(func=self.run_xcode_ios)
                        case "macos":
                            simple.set_defaults(func=self.run_xcode)
                        case "sim":
                            simple.set_defaults(func=self.run_xcode_sim)
                    #simple.set_defaults(func=self.run_xcode)
            simple = apple_sub.add_parser("simple", help="Build, install and run with sensible defaults")
            simple.set_defaults(func=self.run_xcode)

    @staticmethod
    def _find_subparsers_action(parser: argparse.ArgumentParser) -> argparse._SubParsersAction:
        """Return the _SubParsersAction previously added via parser.add_subparsers()."""
        if parser._subparsers is not None:
            for action in parser._subparsers._group_actions:
                if isinstance(action, argparse._SubParsersAction):
                    return action
        raise ValueError(f"{parser.prog!r} has no subparsers registered")

    def run_gradle(self, args: argparse.Namespace) -> int:

        project = OverrideProject()

        project.build()


        target = select_target(project.devices())

        project.run(name= target["name"])

        print(f"Selected target: {target})")
        return 0

    def run_xcode(self, args: argparse.Namespace) -> int:

        project = XcodeProject()

        project.macos_build()

        project.macos_run()

        return 0

    def run_xcode_ios(self, args: argparse.Namespace, sim: bool = False) -> int:

        project = XcodeProject()

        project.ios_build(simulator=sim)

        wanted_kind = "simulator" if sim else "device"
        target = select_target(d for d in project.devices() if d["kind"] == wanted_kind)

        project.ios_run(uuid=target.get("uuid"))

        print(f"Selected target: {target})")
        return 0

    def run_xcode_sim(self, args: argparse.Namespace) -> int:
        return self.run_xcode_ios(args, sim=True)


plugin: CommandPlugin = SimpleCommands()